package vu.lt.mybatis;

import vu.lt.mybatis.model.Position;

import java.util.List;

public interface PositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POSITION
     *
     * @mbg.generated Sat Mar 30 20:43:11 EET 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POSITION
     *
     * @mbg.generated Sat Mar 30 20:43:11 EET 2019
     */
    int insert(Position record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POSITION
     *
     * @mbg.generated Sat Mar 30 20:43:11 EET 2019
     */
    Position selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POSITION
     *
     * @mbg.generated Sat Mar 30 20:43:11 EET 2019
     */
    List<Position> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POSITION
     *
     * @mbg.generated Sat Mar 30 20:43:11 EET 2019
     */
    int updateByPrimaryKey(Position record);
}