package vu.lt.myBatis.dao;

import vu.lt.myBatis.model.Candidate;

import java.util.List;

public interface CandidateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CANDIDATE
     *
     * @mbg.generated Sat Mar 30 20:43:11 EET 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CANDIDATE
     *
     * @mbg.generated Sat Mar 30 20:43:11 EET 2019
     */
    int insert(Candidate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CANDIDATE
     *
     * @mbg.generated Sat Mar 30 20:43:11 EET 2019
     */
    Candidate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CANDIDATE
     *
     * @mbg.generated Sat Mar 30 20:43:11 EET 2019
     */
    List<Candidate> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CANDIDATE
     *
     * @mbg.generated Sat Mar 30 20:43:11 EET 2019
     */
    int updateByPrimaryKey(Candidate record);
}