package vu.lt.myBatis.model.dao;

import vu.lt.persistence.mybatis.model.Interview;

import java.util.List;

public interface InterviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.INTERVIEW
     *
     * @mbg.generated Sat Mar 30 20:43:11 EET 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.INTERVIEW
     *
     * @mbg.generated Sat Mar 30 20:43:11 EET 2019
     */
    int insert(Interview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.INTERVIEW
     *
     * @mbg.generated Sat Mar 30 20:43:11 EET 2019
     */
    Interview selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.INTERVIEW
     *
     * @mbg.generated Sat Mar 30 20:43:11 EET 2019
     */
    List<Interview> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.INTERVIEW
     *
     * @mbg.generated Sat Mar 30 20:43:11 EET 2019
     */
    int updateByPrimaryKey(Interview record);
}